// Code generated by dynago from rekey.dynago.yaml. DO NOT EDIT.

package rekey

import (
	"context"
	"fmt"
	"io"

	"github.com/guregu/dynamo/v2"

	"github.com/nicklanng/dynago"
)

// Generation is the table generation this code reads and writes: its table is
// <base>-g2 (see TableName). A change existing items don't fit starts a new generation,
// which the migration job fills from the previous one.
const Generation = 2

// TableName returns the name of this generation's table for a base name, such as "rekey".
func TableName(base string) string {
	return base + "-g2"
}

// TableSpec is the physical shape of the rekey table: base key PK/SK, its global secondary
// indexes and its TTL attribute. See also the generated Terraform.
var TableSpec = dynago.TableSpec{}

// Store gives typed access to the rekey table.
type Store struct {
	Persons *PersonStore
}

// New returns a Store for the table named tableName.
func New(db *dynamo.DB, tableName string) *Store {
	t := db.Table(tableName)
	return &Store{
		Persons: &PersonStore{db: db, t: t},
	}
}

// EnsureTable creates the table if it is missing and enables TTL. Use it for local
// development and tests; production tables belong in infrastructure code.
func EnsureTable(ctx context.Context, db *dynamo.DB, tableName string) error {
	return dynago.EnsureTable(ctx, db, tableName, TableSpec)
}

// ---- Person ----

// Person is stored in the rekey table.
type Person struct {
	PersonID string `dynamo:"personId,omitempty"`
	Email    string `dynamo:"email"`
	Name     string `dynamo:"name,omitempty"`

	loaded *personLoaded // set when the store returns the entity
}

// personLoaded remembers the stored state an entity was read at, so a write passed the entity
// with dynago.From can start from it without reading again.
type personLoaded struct {
	rev      int64
	v        int
	snapshot Person
	raw      dynamo.Item // as stored, including attributes this code doesn't know
}

// Version identifies the stored state e was read at, for optimistic concurrency: pass it back
// with dynago.IfVersion (e.g. from an ETag) to make a write fail if anything changed since.
// It is "" for an entity that was not read from the store.
func (e *Person) Version() string {
	if e.loaded == nil {
		return ""
	}
	return dynago.FormatVersion(e.loaded.rev)
}

// clone copies e, including its slices and maps, without its loaded state.
func (e *Person) clone() Person {
	c := *e
	c.loaded = nil
	return c
}

// checkKeyParts rejects values containing a character their key templates use as a separator.
func (e *Person) checkKeyParts() error {
	return nil
}

// PersonKey identifies a Person.
type PersonKey struct {
	Email string
}

// Key returns the primary key of e.
func (e *Person) Key() PersonKey {
	return PersonKey{Email: e.Email}
}

func (k PersonKey) dynamoKey() (dynago.Key, error) {
	if k.Email == "" {
		return dynago.Key{}, fmt.Errorf("%w: Person needs email", dynago.ErrInvalidKey)
	}
	return dynago.Key{PK: "E#" + k.Email, SK: "PERSON"}, nil
}

// Errors returned by PersonStore. Each wraps the matching dynago sentinel.
var (
	ErrPersonNotFound = fmt.Errorf("%w: Person", dynago.ErrNotFound)
	ErrPersonExists   = fmt.Errorf("%w: Person", dynago.ErrExists)
)

const personVersion = 2

type personItem struct {
	Person
	PK  string `dynamo:"PK"`
	SK  string `dynamo:"SK"`
	T   string `dynamo:"_t"`
	V   int    `dynamo:"_v"`
	Rev int64  `dynamo:"_rev"`

	raw dynamo.Item // as read, for writes to keep attributes this code doesn't know
}

// personKnown is every attribute this code writes on Person items.
var personKnown = map[string]bool{"PK": true, "SK": true, "_t": true, "_v": true, "_rev": true, "personId": true, "email": true, "name": true}

func personToItem(e *Person, key dynago.Key, rev int64) *personItem {
	it := &personItem{Person: *e, PK: key.PK, SK: key.SK, T: "Person", V: personVersion, Rev: rev}
	return it
}

// People is an atomic counter maintained by every Person write.
type People struct {
	// All counts items.
	All int64 `dynamo:"all"`
}

// PeopleKey identifies a People counter.
type PeopleKey struct {
}

// personDerived returns the counter contributions, claims and copies that exist because of e.
func personDerived(e *Person, owner dynago.Key) []dynago.Derived {
	_ = owner // only sharded counters use it
	var d []dynago.Derived
	// counter People
	if true {
		k := dynago.Key{PK: "PEOPLE", SK: "COUNT"}
		d = append(d, dynago.Derived{Kind: dynago.KindCounter, Key: k, Type: "People", Attr: "all", Amount: 1})
	}
	return d
}

// PersonStore reads and writes Person items. Only the access patterns declared in the schema
// exist as methods.
type PersonStore struct {
	db *dynamo.DB
	t  dynamo.Table
}

func (s *PersonStore) load(ctx context.Context, key dynago.Key, consistent bool) (*personItem, error) {
	var raw dynamo.Item
	found, err := dynago.GetOne(ctx, s.t, key, consistent, &raw)
	if err != nil {
		return nil, err
	}
	if !found {
		return nil, ErrPersonNotFound
	}
	return personDecode(raw)
}

// personDecode decodes a stored item, remembering its state for writes passed dynago.From.
func personDecode(raw dynamo.Item) (*personItem, error) {
	var it personItem
	if err := dynamo.UnmarshalItem(raw, &it); err != nil {
		return nil, err
	}
	it.raw = raw
	it.loaded = &personLoaded{rev: it.Rev, v: it.V, snapshot: it.clone(), raw: raw}
	return &it, nil
}

func personDecodeAll(raws []dynamo.Item) ([]Person, error) {
	out := make([]Person, 0, len(raws))
	for _, raw := range raws {
		it, err := personDecode(raw)
		if err != nil {
			return nil, err
		}
		out = append(out, it.Person)
	}
	return out, nil
}

// Get reads a Person by primary key with one eventually consistent GetItem.
func (s *PersonStore) Get(ctx context.Context, k PersonKey) (*Person, error) {
	key, err := k.dynamoKey()
	if err != nil {
		return nil, err
	}
	it, err := s.load(ctx, key, false)
	if err != nil {
		return nil, err
	}
	return &it.Person, nil
}

// Count reads the People counter (one eventually consistent GetItem). A counter nothing has touched
// reads as zero.
func (s *PersonStore) Count(ctx context.Context, k PeopleKey) (People, error) {
	var out People
	_, err := dynago.GetOne(ctx, s.t, dynago.Key{PK: "PEOPLE", SK: "COUNT"}, false, &out)
	return out, err
}

// Add creates a Person, failing with ErrPersonExists if one already exists. In the same transaction
// it maintains counter People. Afterwards e.Version() returns the new item's version.
func (s *PersonStore) Add(ctx context.Context, e *Person) error {
	key, err := e.Key().dynamoKey()
	if err != nil {
		return err
	}
	if err := e.checkKeyParts(); err != nil {
		return err
	}
	rev := dynago.NewRev()
	return dynago.Retry(ctx, func() error {
		put := s.t.Put(personToItem(e, key, rev)).If("attribute_not_exists($)", "PK")
		ops := []dynago.Op{dynago.CreateOp(key, put, ErrPersonExists, rev)}
		changes := []dynago.Change{{Owner: key, After: personDerived(e, key)}}
		derived, err := dynago.DiffAll(s.t, changes)
		if err != nil {
			return err
		}
		ops = append(ops, derived...)
		if err := dynago.Run(ctx, s.db, ops); err != nil {
			return err
		}
		e.loaded = &personLoaded{rev: rev, v: personVersion, snapshot: e.clone()}
		return nil
	})
}

// ---- migration ----

// RunMigration runs the migration job's command line (see dynago.MigrateUsage): it copies the
// previous table generation into this one. A generated main (output.migrate_cmd) calls it.
func RunMigration(ctx context.Context, db *dynamo.DB, args []string, out io.Writer) error {
	command, base, workers, passes, rate, err := dynago.ParseMigrate(args, "rekey")
	if err != nil {
		return err
	}
	mig := NewMigration(db, base)
	mig.Workers, mig.MaxPasses, mig.Rate, mig.Out = workers, passes, rate, out
	return mig.Run(ctx, command)
}

// NewMigration returns the job copying generation 1 of the table into generation 2: base-g1
// into base-g2. Entities are converted by the Migrate<Entity> functions, where set, and copied
// field by field otherwise.
func NewMigration(db *dynamo.DB, base string) *dynago.Migration {
	st := New(db, TableName(base))
	return &dynago.Migration{DB: db, From: base + "-g1", To: TableName(base),
		Types: map[string]bool{"Person": true},
		Copy:  st.migrateCopy, KeyOf: st.migrateKeyOf, Remove: st.migrateRemove, Check: migrationCheck, TTLAttr: "ttl"}
}

// PersonG1 is a Person as generation 1 stored it: what the migration job reads.
type PersonG1 struct {
	PersonID string `dynamo:"personId"`
	Email    string `dynamo:"email"`
	Name     string `dynamo:"name"`
}

// MigratePerson, if set, converts a generation-1 Person into this generation's. Without it, the
// migration job uses AutoMigratePerson: every field carries over. Set it in a file of your own in
// this package to fill new fields.
var MigratePerson func(old PersonG1) (Person, error)

// AutoMigratePerson copies the fields of a generation-1 Person that exist in this generation with the
// same type (enums by value); the others are left zero.
func AutoMigratePerson(old PersonG1) Person {
	return Person{PersonID: old.PersonID, Email: old.Email, Name: old.Name}
}

// migrationCheck reports the conversions the migration job needs but hasn't been given.
func migrationCheck() error {
	return nil // every entity carries over field by field
}

// convertPerson converts a Person stored by generation 1 into this generation's.
func convertPerson(raw dynamo.Item) (Person, error) {
	var old PersonG1
	if err := dynamo.UnmarshalItem(raw, &old); err != nil {
		return Person{}, err
	}
	if MigratePerson == nil {
		return AutoMigratePerson(old), nil
	}
	e, err := MigratePerson(old)
	if err != nil {
		return Person{}, fmt.Errorf("%w: %w", dynago.ErrMigrationConflict, err)
	}
	return e, nil
}

// migrateCopy converts one item of the previous generation and writes it into this one.
func (s *Store) migrateCopy(ctx context.Context, raw dynamo.Item, fence dynago.Op) error {
	if dynago.ExpiredItem(raw, "ttl") {
		return dynago.ErrUnchanged // expired: gone, even if DynamoDB hasn't deleted it yet
	}
	if dynago.ItemType(raw) == "Person" {
		e, err := convertPerson(raw)
		if err != nil {
			return err
		}
		src, srcRev, err := dynago.SourceOf(raw)
		if err != nil {
			return err
		}
		return s.Persons.migrate(ctx, &e, src, srcRev, fence)
	}
	return dynago.ErrUnchanged
}

// migrateKeyOf returns the key an item of the previous generation converts to, or false if it
// isn't copied.
func (s *Store) migrateKeyOf(raw dynamo.Item) (dynago.Key, bool, error) {
	if dynago.ExpiredItem(raw, "ttl") {
		return dynago.Key{}, false, nil
	}
	if dynago.ItemType(raw) == "Person" {
		e, err := convertPerson(raw)
		if err != nil {
			return dynago.Key{}, false, err
		}
		key, err := e.Key().dynamoKey()
		return key, err == nil, err
	}
	return dynago.Key{}, false, nil
}

// migrateRemove deletes an entity the migration copied, because its source is gone or now
// converts to another key.
func (s *Store) migrateRemove(ctx context.Context, raw dynamo.Item, fence dynago.Op) error {
	if dynago.ItemType(raw) == "Person" {
		return s.Persons.migrateRemove(ctx, raw, fence)
	}
	return nil
}

// migrate writes e, converted from the item at src in the previous generation (revision
// srcRev), replacing what the new table holds for it, with its derived items.
func (s *PersonStore) migrate(ctx context.Context, e *Person, src dynago.Key, srcRev int64, fence dynago.Op) error {
	key, err := e.Key().dynamoKey()
	if err != nil {
		return err
	}
	if err := e.checkKeyParts(); err != nil {
		return err
	}
	return dynago.Retry(ctx, func() error {
		var raw dynamo.Item
		found, err := dynago.GetOne(ctx, s.t, key, true, &raw)
		if err != nil {
			return err
		}
		rev := dynago.NewRev()
		var before []dynago.Derived
		if found {
			same, other := dynago.MigratedFrom(raw, src, srcRev)
			switch {
			case other:
				return fmt.Errorf("%w: another item of the previous generation converts to the same Person key", dynago.ErrMigrationConflict)
			case same:
				return dynago.ErrUnchanged
			}
			it, err := personDecode(raw)
			if err != nil {
				return err
			}
			before = dynago.Unbounded(personDerived(&it.Person, key))
			rev = it.Rev + 1
		}
		item, err := dynago.MigrationItem(personToItem(e, key, rev), src, srcRev)
		if err != nil {
			return err
		}
		put := s.t.Put(item).If("attribute_not_exists($)", "PK")
		if found {
			put = s.t.Put(item).If("$ = ?", "_rev", rev-1)
		}
		ops := []dynago.Op{dynago.PutOp(key, put, dynago.ErrStale), fence}
		derived, err := dynago.Diff(s.t, key, before, dynago.Unbounded(personDerived(e, key)))
		if err != nil {
			return err
		}
		ops = append(ops, derived...)
		return dynago.Run(ctx, s.db, ops)
	})
}

// migrateRemove deletes an entity the migration copied, with its derived items.
func (s *PersonStore) migrateRemove(ctx context.Context, raw dynamo.Item, fence dynago.Op) error {
	return dynago.Retry(ctx, func() error {
		var current dynamo.Item
		found, err := dynago.GetOne(ctx, s.t, dynago.Key{PK: dynago.ItemKey(raw).PK, SK: dynago.ItemKey(raw).SK}, true, &current)
		if err != nil || !found {
			return err
		}
		it, err := personDecode(current)
		if err != nil {
			return err
		}
		key := dynago.Key{PK: it.PK, SK: it.SK}
		ops := []dynago.Op{dynago.DeleteOp(key, s.t.Delete("PK", key.PK).Range("SK", key.SK).If("$ = ?", "_rev", it.Rev), dynago.ErrStale), fence}
		derived, err := dynago.Diff(s.t, key, dynago.Unbounded(personDerived(&it.Person, key)), nil)
		if err != nil {
			return err
		}
		ops = append(ops, derived...)
		return dynago.Run(ctx, s.db, ops)
	})
}
