// Package dynago is the runtime for code generated by the dynago tool.
//
// dynago turns a schema file describing a DynamoDB table (its entities, keys, indexes, uniqueness
// claims, counters, and every read and write) into a typed Go store, a data model document,
// Terraform and a cost report. The generated store calls this package; application code uses it
// for the few things that cross stores:
//
//   - sentinel errors such as ErrNotFound, ErrTaken, ErrLimit and ErrVersionMismatch, which every
//     generated error wraps;
//   - Page, to page through queries;
//   - Limit and Max, for counter limits supplied by the caller;
//   - From and IfVersion, for optimistic concurrency.
//
// The remaining exported identifiers (Op, Diff, Run, QuerySpec and so on) are building blocks for
// generated code. They are stable, but not meant to be called by hand.
//
// Documentation: https://github.com/nicklanng/dynago/tree/main/docs
package dynago

import (
	"crypto/rand"
	"encoding/binary"
	"errors"
	"fmt"
	"strconv"
	"strings"

	"golang.org/x/text/unicode/norm"
	"time"
)

// Sentinel errors. Generated code wraps these in entity-specific errors, so both
// errors.Is(err, dynago.ErrNotFound) and errors.Is(err, mytable.ErrEventNotFound) work.
var (
	// ErrNotFound means the item does not exist.
	ErrNotFound = errors.New("dynago: not found")
	// ErrExists means a create found an item already at that key.
	ErrExists = errors.New("dynago: already exists")
	// ErrPrecondition means a write's declared condition did not hold: an update's `when`, or
	// something it `requires` of another item.
	ErrPrecondition = errors.New("dynago: precondition failed")
	// ErrTaken means a unique value is already claimed by another item.
	ErrTaken = errors.New("dynago: unique value already taken")
	// ErrLimit means a write would take a limited counter past its limit.
	ErrLimit = errors.New("dynago: counter limit reached")
	// ErrConflict means the item kept changing under a read-modify-write until retries ran out.
	ErrConflict = errors.New("dynago: concurrent modification")
	// ErrInvalidCursor means a page cursor was malformed or belongs to a different query.
	ErrInvalidCursor = errors.New("dynago: invalid cursor")
	// ErrInvalidKey means a key field was empty, or contained a character its key uses as a
	// separator.
	ErrInvalidKey = errors.New("dynago: invalid key")
	// ErrFieldRequired means a write left a field declared `required: true` at its zero value.
	ErrFieldRequired = errors.New("dynago: required field is empty")
	// ErrLimitRequired means a write that takes a caller-supplied limit was not given one.
	ErrLimitRequired = errors.New("dynago: limit required")
	// ErrSameItemTwice means a write would touch one item twice in a transaction, which DynamoDB
	// rejects. It is a schema shape dynago should have refused when generating: please report it.
	ErrSameItemTwice = errors.New("dynago: a transaction would touch the same item twice")
	// ErrTooManyItems means a write would touch more than DynamoDB's 100-item transaction limit.
	ErrTooManyItems = errors.New("dynago: write touches more than 100 items")

	// ErrNeedsRead is returned internally when a write tried without reading the item found that
	// the state it assumed did not hold. Generated writes then read the item and try again; callers
	// never see it.
	ErrNeedsRead = errors.New("dynago: write must read the item first")

	// ErrStale is returned internally when an item changed between a read and the conditional
	// write that followed it. Generated writes retry on it; callers see ErrConflict if retries run out.
	ErrStale = errors.New("dynago: item changed since it was read")
	// ErrContention is returned when DynamoDB cancels a transaction because another transaction
	// touched the same item. Generated writes retry on it.
	ErrContention = errors.New("dynago: transaction conflict")
)

// Attribute names written on every item.
const (
	AttrPK   = "PK"
	AttrSK   = "SK"
	AttrType = "_t"
	AttrVer  = "_v"
	AttrRev  = "_rev"
	// AttrCreated and AttrUpdated hold when dynago first wrote an item and when it last changed
	// it, in TimeLayout. Items written before dynago kept them lack them until rewritten.
	AttrCreated = "_created"
	AttrUpdated = "_updated"
)

// Key is a table primary key.
type Key struct {
	PK string
	SK string
}

// Limit is a caller-supplied cap for a counter value declared with `limit: arg`. Build it with
// Max or Unlimited: the zero Limit is "not given", which generated writes reject with
// ErrLimitRequired, so a forgotten limit can never silently switch enforcement off.
type Limit struct {
	Max       int64
	Set       bool
	Unbounded bool
}

// Max returns a Limit of n.
func Max(n int64) Limit { return Limit{Max: n, Set: true} }

// Unlimited returns a Limit that deliberately enforces nothing.
func Unlimited() Limit { return Limit{Set: true, Unbounded: true} }

// RequireLimit returns ErrLimitRequired if l was not given. Generated writes call it for every
// limit they take.
func RequireLimit(name string, l Limit) error {
	if !l.Set {
		return fmt.Errorf("%w: %s (use dynago.Max(n), or dynago.Unlimited() on purpose)", ErrLimitRequired, name)
	}
	return nil
}

// Ptr returns a pointer to v, for optional (patch) update fields: dynago.Ptr("new title").
func Ptr[T any](v T) *T { return &v }

// Page selects one page of a query. The zero Page asks for the first page at the default size.
type Page struct {
	// Size is the maximum number of items to evaluate. Zero means the access pattern's default;
	// sizes above its maximum are clamped.
	Size int
	// Cursor is the Next value returned by the previous page, or "" for the first page.
	Cursor string
}

// RangeEnd is appended to a sort key prefix to form an inclusive upper bound that sorts after
// every key starting with that prefix.
const RangeEnd = "\U0010FFFF"

// FmtString renders a string for a key.
func FmtString[S ~string](s S) string { return string(s) }

// FmtInt renders an integer for a key so that lexical order matches numeric order.
func FmtInt(i int64) string {
	if i >= 0 {
		return fmt.Sprintf("%019d", i)
	}
	// Negative numbers sort before '0' because of the '-', and the complement keeps them in order.
	return fmt.Sprintf("-%019d", uint64(i)+(1<<63))
}

// Lower is the `lower` key template transform: {name|lower} sorts and matches case-insensitively.
// It normalises to NFC first, so an "é" typed as one code point and as "e" plus a combining accent
// render the same key. Keys still sort by bytes, not by any language's alphabet: "émile" sorts
// after "zoe".
func Lower(s string) string { return strings.ToLower(norm.NFC.String(s)) }

// FmtBool renders a bool for a key.
func FmtBool(b bool) string { return strconv.FormatBool(b) }

// TimeLayout is the fixed-width UTC layout used for times in keys, so they sort chronologically.
const TimeLayout = "2006-01-02T15:04:05.000000000Z"

// FmtTime renders a time for a key.
func FmtTime(t time.Time) string { return t.UTC().Format(TimeLayout) }

// UnixTTL converts a time to the epoch seconds DynamoDB's TTL expects; zero stays zero.
func UnixTTL(t time.Time) int64 {
	if t.IsZero() {
		return 0
	}
	return t.Unix()
}

// NewRev returns the starting revision for a new item. It is random rather than 1 so that a
// read-modify-write guarded by a revision read before a delete and re-create cannot mistake the
// new item for the one it read. It stays below 2^52 so it survives a trip through a float64
// (JSON, JavaScript) exactly.
func NewRev() int64 {
	var b [8]byte
	if _, err := rand.Read(b[:]); err != nil {
		panic("dynago: no randomness: " + err.Error())
	}
	return int64(binary.BigEndian.Uint64(b[:])>>12) + 1
}
