// Code generated by dynago from app.dynago.yaml. DO NOT EDIT.

package app

import (
	"context"

	"github.com/guregu/dynamo/v2"
)

func generated(ctx context.Context, db *dynamo.DB) error {
	return db.Table("x").Put(map[string]string{"PK": "a"}).Run(ctx)
}
