// Code generated by dynago from toollibrary.dynago.yaml. DO NOT EDIT.

// Command migrate-toollibrary copies the previous generation of the toollibrary table into the
// current one. Run `copy` as a job before rolling out a version with a new table generation, and
// `finish` once writes to the old generation have stopped (for example from an init container of
// the new pods). The AWS SDK's usual environment configures it: credentials, AWS_REGION, and
// AWS_ENDPOINT_URL_DYNAMODB for DynamoDB Local.
//
//	migrate-toollibrary [-table base] [-workers n] [-rate items/s] [-passes n] copy|finish|status
package main

import (
	"context"
	"fmt"
	"os"
	"os/signal"
	"syscall"

	"github.com/aws/aws-sdk-go-v2/config"
	"github.com/guregu/dynamo/v2"

	toollibrary "github.com/nicklanng/dynago/examples/toollibrary"
)

func main() {
	if err := run(); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}

func run() error {
	ctx, stop := signal.NotifyContext(context.Background(), os.Interrupt, syscall.SIGTERM)
	defer stop()
	cfg, err := config.LoadDefaultConfig(ctx)
	if err != nil {
		return err
	}
	return toollibrary.RunMigration(ctx, dynamo.New(cfg), os.Args[1:], os.Stdout)
}
