// Code generated by dynago from fixture.dynago.yaml. DO NOT EDIT.

package fixture

import (
	"context"
	"fmt"
	"io"

	"github.com/guregu/dynamo/v2"

	"github.com/nicklanng/dynago"
)

// Generation is the table generation this code reads and writes: its table is
// <base>-g1 (see TableName). A change existing items don't fit starts a new generation,
// which the migration job fills from the previous one.
const Generation = 1

// TableName returns the name of this generation's table for a base name, such as "fixture".
func TableName(base string) string {
	return base + "-g1"
}

// TableSpec is the physical shape of the fixture table: base key PK/SK, its global secondary
// indexes and its TTL attribute. See also the generated Terraform.
var TableSpec = dynago.TableSpec{}

// Store gives typed access to the fixture table.
type Store struct {
	Accounts *AccountStore
}

// New returns a Store for the table named tableName.
func New(db *dynamo.DB, tableName string) *Store {
	t := db.Table(tableName)
	return &Store{
		Accounts: &AccountStore{db: db, t: t},
	}
}

// EnsureTable creates the table if it is missing and enables TTL. Use it for local
// development and tests; production tables belong in infrastructure code.
func EnsureTable(ctx context.Context, db *dynamo.DB, tableName string) error {
	return dynago.EnsureTable(ctx, db, tableName, TableSpec)
}

// ---- Account ----

// AccountStatus is the set of values of Account.status.
type AccountStatus string

// Values of AccountStatus.
const (
	AccountStatusPending AccountStatus = "pending"
	AccountStatusActive  AccountStatus = "active"
	AccountStatusClosed  AccountStatus = "closed"
)

// Account is stored in the fixture table.
type Account struct {
	TenantID    string        `dynamo:"tenantId"`
	AccountID   string        `dynamo:"accountId"`
	Region      string        `dynamo:"region,omitempty"`
	Status      AccountStatus `dynamo:"status,omitempty"`
	SuccessorID string        `dynamo:"successorId,omitempty"`

	loaded *accountLoaded // set when the store returns the entity
}

// accountLoaded remembers the stored state an entity was read at, so a write passed the entity
// with dynago.From can start from it without reading again.
type accountLoaded struct {
	rev      int64
	v        int
	snapshot Account
	raw      dynamo.Item // as stored, including attributes this code doesn't know
}

// Version identifies the stored state e was read at, for optimistic concurrency: pass it back
// with dynago.IfVersion (e.g. from an ETag) to make a write fail if anything changed since.
// It is "" for an entity that was not read from the store.
func (e *Account) Version() string {
	if e.loaded == nil {
		return ""
	}
	return dynago.FormatVersion(e.loaded.rev)
}

// clone copies e, including its slices and maps, without its loaded state.
func (e *Account) clone() Account {
	c := *e
	c.loaded = nil
	return c
}

// checkKeyParts rejects values containing a character their key templates use as a separator.
func (e *Account) checkKeyParts() error {
	return nil
}

// AccountKey identifies an Account.
type AccountKey struct {
	TenantID  string
	AccountID string
}

// Key returns the primary key of e.
func (e *Account) Key() AccountKey {
	return AccountKey{TenantID: e.TenantID, AccountID: e.AccountID}
}

func (k AccountKey) dynamoKey() (dynago.Key, error) {
	if k.TenantID == "" || k.AccountID == "" {
		return dynago.Key{}, fmt.Errorf("%w: Account needs tenantId and accountId", dynago.ErrInvalidKey)
	}
	return dynago.Key{PK: "T#" + k.TenantID, SK: "ACCOUNT#" + k.AccountID}, nil
}

// Errors returned by AccountStore. Each wraps the matching dynago sentinel.
var (
	ErrAccountNotFound                = fmt.Errorf("%w: Account", dynago.ErrNotFound)
	ErrAccountExists                  = fmt.Errorf("%w: Account", dynago.ErrExists)
	ErrAccountActivatePrecondition    = fmt.Errorf("%w: Account.Activate requires status = \"pending\"", dynago.ErrPrecondition)
	ErrAccountHandOverPrecondition    = fmt.Errorf("%w: Account.HandOver requires status = \"active\"", dynago.ErrPrecondition)
	ErrAccountHandOverRequiresAccount = fmt.Errorf("%w: Account.HandOver requires the Account to exist with status = \"pending\"", dynago.ErrPrecondition)
)

const accountVersion = 1

type accountItem struct {
	Account
	PK  string `dynamo:"PK"`
	SK  string `dynamo:"SK"`
	T   string `dynamo:"_t"`
	V   int    `dynamo:"_v"`
	Rev int64  `dynamo:"_rev"`

	raw dynamo.Item // as read, for writes to keep attributes this code doesn't know
}

// accountKnown is every attribute this code writes on Account items.
var accountKnown = map[string]bool{"PK": true, "SK": true, "_t": true, "_v": true, "_rev": true, "tenantId": true, "accountId": true, "region": true, "status": true, "successorId": true}

func accountToItem(e *Account, key dynago.Key, rev int64) *accountItem {
	it := &accountItem{Account: *e, PK: key.PK, SK: key.SK, T: "Account", V: accountVersion, Rev: rev}
	return it
}

// TenantCounts is an atomic counter maintained by every Account write.
type TenantCounts struct {
	// Active counts items where status = "active".
	Active int64 `dynamo:"active"`
	// Closed counts items where status = "closed".
	Closed int64 `dynamo:"closed"`
}

// TenantCountsKey identifies a TenantCounts counter.
type TenantCountsKey struct {
	TenantID string
}

// RegionCounts is an atomic counter maintained by every Account write.
type RegionCounts struct {
	// Active counts items where status = "active".
	Active int64 `dynamo:"active"`
}

// RegionCountsKey identifies a RegionCounts counter.
type RegionCountsKey struct {
	Region string
}

// accountDerived returns the counter contributions, claims and copies that exist because of e.
func accountDerived(e *Account, owner dynago.Key) []dynago.Derived {
	_ = owner // only sharded counters use it
	var d []dynago.Derived
	// counter TenantCounts
	if e.TenantID != "" {
		k := dynago.Key{PK: "T#" + e.TenantID, SK: "COUNTS"}
		if e.Status == AccountStatusActive {
			d = append(d, dynago.Derived{Kind: dynago.KindCounter, Key: k, Type: "TenantCounts", Attr: "active", Amount: 1})
		}
		if e.Status == AccountStatusClosed {
			d = append(d, dynago.Derived{Kind: dynago.KindCounter, Key: k, Type: "TenantCounts", Attr: "closed", Amount: 1})
		}
	}
	// counter RegionCounts
	if e.Region != "" {
		k := dynago.Key{PK: "R#" + e.Region, SK: "COUNTS"}
		if e.Status == AccountStatusActive {
			d = append(d, dynago.Derived{Kind: dynago.KindCounter, Key: k, Type: "RegionCounts", Attr: "active", Amount: 1})
		}
	}
	return d
}

// AccountStore reads and writes Account items. Only the access patterns declared in the schema
// exist as methods.
type AccountStore struct {
	db *dynamo.DB
	t  dynamo.Table
}

func (s *AccountStore) load(ctx context.Context, key dynago.Key, consistent bool) (*accountItem, error) {
	var raw dynamo.Item
	found, err := dynago.GetOne(ctx, s.t, key, consistent, &raw)
	if err != nil {
		return nil, err
	}
	if !found {
		return nil, ErrAccountNotFound
	}
	return accountDecode(raw)
}

// accountDecode decodes a stored item, remembering its state for writes passed dynago.From.
func accountDecode(raw dynamo.Item) (*accountItem, error) {
	var it accountItem
	if err := dynamo.UnmarshalItem(raw, &it); err != nil {
		return nil, err
	}
	it.raw = raw
	it.loaded = &accountLoaded{rev: it.Rev, v: it.V, snapshot: it.clone(), raw: raw}
	return &it, nil
}

func accountDecodeAll(raws []dynamo.Item) ([]Account, error) {
	out := make([]Account, 0, len(raws))
	for _, raw := range raws {
		it, err := accountDecode(raw)
		if err != nil {
			return nil, err
		}
		out = append(out, it.Account)
	}
	return out, nil
}

// from returns the entity passed with dynago.From, checked to be this item and read from the
// store, or nil if none was passed.
func (s *AccountStore) from(key dynago.Key, o dynago.WriteOptions) (*Account, error) {
	if o.From == nil {
		return nil, nil
	}
	from, ok := o.From.(*Account)
	if !ok || from == nil || from.loaded == nil {
		return nil, fmt.Errorf("%w: dynago.From needs a *Account read from its own item, not built by hand or read through a copy index", dynago.ErrVersionRequired)
	}
	if fk, err := from.Key().dynamoKey(); err != nil || fk != key {
		return nil, fmt.Errorf("%w: the Account passed with dynago.From is a different item", dynago.ErrInvalidKey)
	}
	return from, nil
}

// start returns the state a read-modify-write starts from: the entity passed with dynago.From
// (no read), or a consistent read. versioned reports whether the caller named a version, in
// which case a concurrent change is a mismatch for the caller rather than something to retry.
func (s *AccountStore) start(ctx context.Context, key dynago.Key, o dynago.WriteOptions, required bool) (*accountItem, bool, error) {
	expect, err := o.ExpectedRev()
	if err != nil {
		return nil, false, err
	}
	from, err := s.from(key, o)
	if err != nil {
		return nil, false, err
	}
	if from != nil {
		if expect != 0 && expect != from.loaded.rev {
			return nil, false, dynago.ErrVersionMismatch
		}
		return &accountItem{Account: from.loaded.snapshot, Rev: from.loaded.rev, V: from.loaded.v, raw: from.loaded.raw}, true, nil
	}
	if required && expect == 0 {
		return nil, false, dynago.ErrVersionRequired
	}
	it, err := s.load(ctx, key, true)
	if err != nil {
		return nil, false, err
	}
	if expect != 0 && it.Rev != expect {
		return nil, false, dynago.ErrVersionMismatch
	}
	return it, expect != 0, nil
}

// Get reads an Account by primary key with one eventually consistent GetItem.
func (s *AccountStore) Get(ctx context.Context, k AccountKey) (*Account, error) {
	key, err := k.dynamoKey()
	if err != nil {
		return nil, err
	}
	it, err := s.load(ctx, key, false)
	if err != nil {
		return nil, err
	}
	return &it.Account, nil
}

// Tenant reads the TenantCounts counter (one eventually consistent GetItem). A counter nothing has
// touched reads as zero.
func (s *AccountStore) Tenant(ctx context.Context, k TenantCountsKey) (TenantCounts, error) {
	if k.TenantID == "" {
		return TenantCounts{}, fmt.Errorf("%w: TenantCounts needs tenantId", dynago.ErrInvalidKey)
	}
	var out TenantCounts
	_, err := dynago.GetOne(ctx, s.t, dynago.Key{PK: "T#" + k.TenantID, SK: "COUNTS"}, false, &out)
	return out, err
}

// Region reads the RegionCounts counter (one eventually consistent GetItem). A counter nothing has
// touched reads as zero.
func (s *AccountStore) Region(ctx context.Context, k RegionCountsKey) (RegionCounts, error) {
	if k.Region == "" {
		return RegionCounts{}, fmt.Errorf("%w: RegionCounts needs region", dynago.ErrInvalidKey)
	}
	var out RegionCounts
	_, err := dynago.GetOne(ctx, s.t, dynago.Key{PK: "R#" + k.Region, SK: "COUNTS"}, false, &out)
	return out, err
}

// Open creates an Account, failing with ErrAccountExists if one already exists. In the same
// transaction it maintains counter TenantCounts, counter RegionCounts. Afterwards e.Version()
// returns the new item's version.
func (s *AccountStore) Open(ctx context.Context, e *Account) error {
	key, err := e.Key().dynamoKey()
	if err != nil {
		return err
	}
	if err := e.checkKeyParts(); err != nil {
		return err
	}
	rev := dynago.NewRev()
	return dynago.Retry(ctx, func() error {
		put := s.t.Put(accountToItem(e, key, rev)).If("attribute_not_exists($)", "PK")
		ops := []dynago.Op{dynago.CreateOp(key, put, ErrAccountExists, rev)}
		changes := []dynago.Change{{Owner: key, After: accountDerived(e, key)}}
		derived, err := dynago.DiffAll(s.t, changes)
		if err != nil {
			return err
		}
		ops = append(ops, derived...)
		if err := dynago.Run(ctx, s.db, ops); err != nil {
			return err
		}
		e.loaded = &accountLoaded{rev: rev, v: accountVersion, snapshot: e.clone()}
		return nil
	})
}

// Activate updates status of an Account when status = "pending" (else
// ErrAccountActivatePrecondition). It reads the item consistently first (not with dynago.From)
// because the change affects counter TenantCounts, counter RegionCounts, then writes everything in
// one transaction guarded by the item's revision. In the same transaction it maintains counter
// TenantCounts, counter RegionCounts.
func (s *AccountStore) Activate(ctx context.Context, k AccountKey, opts ...dynago.WriteOption) error {
	key, err := k.dynamoKey()
	if err != nil {
		return err
	}
	o := dynago.ApplyOptions(opts)
	return dynago.Retry(ctx, func() error {
		it, versioned, err := s.start(ctx, key, o, false)
		if err != nil {
			return err
		}
		before := &it.Account
		if before.Status != AccountStatusPending {
			return ErrAccountActivatePrecondition
		}
		after := before.clone()
		after.Status = AccountStatusActive
		// Keep attributes this code doesn't know: a newer compatible version may have written them.
		item, err := dynago.KeepUnknown(it.raw, accountKnown, accountToItem(&after, key, it.Rev+1))
		if err != nil {
			return err
		}
		ops := []dynago.Op{dynago.PutOp(key, s.t.Put(item).If("$ = ?", "_rev", it.Rev), dynago.ErrStale)}
		changes := []dynago.Change{{Owner: key, Before: accountDerived(before, key), After: accountDerived(&after, key)}}
		derived, err := dynago.DiffAll(s.t, changes)
		if err != nil {
			return err
		}
		ops = append(ops, derived...)
		if err := dynago.Run(ctx, s.db, ops); err != nil {
			return dynago.StaleAs(versioned, err)
		}
		o.Written(it.Rev + 1)
		return nil
	})
}

// AccountHandOver holds the new values for Account.HandOver.
type AccountHandOver struct {
	SuccessorID string
}

// HandOver updates successorId and status of an Account when status = "active" (else
// ErrAccountHandOverPrecondition). It reads the item consistently first (not with dynago.From)
// because the change affects counter TenantCounts, counter RegionCounts, then writes everything in
// one transaction guarded by the item's revision. In the same transaction it maintains counter
// TenantCounts, counter RegionCounts. In the same transaction it requires the Account to exist with
// status = "pending" (else ErrAccountHandOverRequiresAccount), and sets its status to "active".
func (s *AccountStore) HandOver(ctx context.Context, k AccountKey, v AccountHandOver, opts ...dynago.WriteOption) error {
	key, err := k.dynamoKey()
	if err != nil {
		return err
	}
	o := dynago.ApplyOptions(opts)
	return dynago.Retry(ctx, func() error {
		it, versioned, err := s.start(ctx, key, o, false)
		if err != nil {
			return err
		}
		before := &it.Account
		if before.Status != AccountStatusActive {
			return ErrAccountHandOverPrecondition
		}
		after := before.clone()
		after.SuccessorID = v.SuccessorID
		after.Status = AccountStatusClosed
		// Keep attributes this code doesn't know: a newer compatible version may have written them.
		item, err := dynago.KeepUnknown(it.raw, accountKnown, accountToItem(&after, key, it.Rev+1))
		if err != nil {
			return err
		}
		ops := []dynago.Op{dynago.PutOp(key, s.t.Put(item).If("$ = ?", "_rev", it.Rev), dynago.ErrStale)}
		base := ops
		return dynago.StaleAs(versioned, dynago.ReadIfNeeded(func(read bool) error {
			ops := append([]dynago.Op(nil), base...)
			changes := []dynago.Change{{Owner: key, Before: accountDerived(before, key), After: accountDerived(&after, key)}}
			// requires Account
			if after.TenantID == "" || after.SuccessorID == "" {
				return fmt.Errorf("%w: Account.HandOver requires the Account, keyed by tenantId and successorId", dynago.ErrFieldRequired)
			}
			accountOps, accountChange, err := s.requireHandOverAccount(ctx, &after, read)
			if err != nil {
				return err
			}
			ops = append(ops, accountOps...)
			changes = append(changes, accountChange)
			derived, err := dynago.DiffAll(s.t, changes)
			if err != nil {
				return err
			}
			ops = append(ops, derived...)
			if err := dynago.Run(ctx, s.db, ops); err != nil {
				return err
			}
			o.Written(it.Rev + 1)
			return nil
		}))
	})
}

// requireHandOverAccount returns the writes Account.HandOver makes to the Account: it requires the
// Account to exist with status = "pending", and sets its status to "active". It reads the Account
// first, because the change to its derived items depends on more than the state required.
func (s *AccountStore) requireHandOverAccount(ctx context.Context, e *Account, read bool) ([]dynago.Op, dynago.Change, error) {
	k := AccountKey{TenantID: e.TenantID, AccountID: e.SuccessorID}
	key, err := k.dynamoKey()
	if err != nil {
		return nil, dynago.Change{}, err
	}
	_ = read // the Account is always read: see above
	it, err := (&AccountStore{db: s.db, t: s.t}).load(ctx, key, true)
	if err == ErrAccountNotFound {
		return nil, dynago.Change{}, ErrAccountHandOverRequiresAccount
	}
	if err != nil {
		return nil, dynago.Change{}, err
	}
	before := &it.Account
	if before.Status != AccountStatusPending {
		return nil, dynago.Change{}, ErrAccountHandOverRequiresAccount
	}
	after := before.clone()
	after.Status = AccountStatusActive
	item, err := dynago.KeepUnknown(it.raw, accountKnown, accountToItem(&after, key, it.Rev+1))
	if err != nil {
		return nil, dynago.Change{}, err
	}
	return []dynago.Op{dynago.PutOp(key, s.t.Put(item).If("$ = ?", "_rev", it.Rev), dynago.ErrStale)}, dynago.Change{Owner: key, Before: accountDerived(before, key), After: accountDerived(&after, key)}, nil
}

// ---- migration ----

// RunMigration runs the migration job's command line (see dynago.MigrateUsage): it copies the
// previous table generation into this one. A generated main (output.migrate_cmd) calls it.
func RunMigration(ctx context.Context, db *dynamo.DB, args []string, out io.Writer) error {
	command, base, workers, passes, rate, err := dynago.ParseMigrate(args, "fixture")
	if err != nil {
		return err
	}
	_, _, _, _ = base, workers, passes, rate
	if command != "copy" && command != "finish" && command != "status" {
		return fmt.Errorf("unknown command %q\n\n%s", command, dynago.MigrateUsage)
	}
	_, err = fmt.Fprintln(out, "generation 1 has no previous generation to migrate from")
	return err
}
